# environment.yml

name: genetic_clustering_env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.8
  - pandas
  - numpy
  - scikit-learn
  - matplotlib
  - seaborn
  - jupyter
  - joblib
  - pip
  - pip:
      - argparse
